Refactor Jbang implementation
cescoffier/quarkus-images pull request #1
Opened 2020-08-26 17:41 UTC by zakkak

Still testing here: https://github.com/zakkak/quarkus-images/runs/1032797452

2020-08-26 17:45 UTC, zakkak commented on .github/build-images.java
> +    private void validateConfiguration(Configuration configuration) {
Hmm, this should be moved in Configuration. I 'll do it after the tests complete :)

2020-08-26 19:20 UTC, zakkak commented
The results for the latest version are here: https://github.com/zakkak/quarkus-images/runs/1032873226?check_suite_focus=true

2020-08-27 06:10 UTC, cescoffier requested changes
Looks great.
I've noticed that 2 things still need to be updated:

* the readme
* the pushed workflow

2020-08-27 06:10 UTC, cescoffier commented on .github/mandrel-images.yaml
> +image: quarkus-mandrel.yaml
Nice!

2020-08-27 11:43 UTC, cescoffier approved these changes

2020-08-27 11:43 UTC, cescoffier commented
Thanks @zakkak !

2020-08-27 11:43 UTC, merged